### PR TITLE
Added automatically refreshed preview

### PR DESCRIPTION
**Pull request by TheCodez**
Enabled by default, but can be disabled in preferences. Also some bugfixes and cleanups

### CODE REVIEW

**Comment by amakaseev** [comment]
Good work, but i think move checkbox (for enable/disable automatically refreshed preview)  from preferences to toolbar near refresh button or refresh tool button set checkable.
I think it it will be more convenient.

**Comment by TheCodez** [comment]
I'll look into it

**Comment by TheCodez** [comment]
Or maybe just add preferences into the toolbar, then it's easier to access

**Comment by amakaseev** [comment]
Ok

**Comment by TheCodez** [comment]
I'll add that into the toolbar, but i don't have a suitable icon. The preferences icon is 32x32 and it should be 64x64

**Pull request merged**
