### PR TITLE
Add pngquant optimizer

### PR DESCRIPTION
**Pull request by TheCodez**
Pngquant reduces filesize by about 70%.

### CODE REVIEW

**Comment by TheCodez** [comment]
Pls test if everything works ok on mac.(default optimizer is still optipng, changeable in preferences)

**Comment by amakaseev** [comment]
Well, what the results of optimization you get?

**Comment by TheCodez** [comment]
No optimization: 95,2KB
Optipng Level 3: 91.8KB
Pngquant:           26.5KB

**Comment by amakaseev** [comment]
No optimization: 145KB
Optipng Level 6: 140KB
Pngquant 6: 40KB! oO
Level 3 == 6 for all
Pngquant - result != original quality :(

**Comment by TheCodez** [comment]
Yes the slider has currently no effect. Thats to expect in contrast to optipng pngquant is not lossless, your sacrifying quality for filesize(but the results are mostly pretty good).

**Comment by amakaseev** [comment]
I dont know... only 
    connect(ui->trimSpinBox, SIGNAL(valueChanged(int)), this, SLOT(propertiesValueChanged(int)));
for all items

**Comment by TheCodez** [comment]
Well, then i have to do that for all properties that are saved in the project file.

**Pull request merged**
