### PR TITLE
Add preferences to toolbar

### PR DESCRIPTION
**Pull request by TheCodez**
Also renamed Property panel to Properties

### CODE REVIEW

**Comment by TheCodez** [comment]
Should I disable the "Refresh Preview" button when automatic preview is on?

**Comment by amakaseev** [comment]
Hi, not, I meant that this button or near it acted as automatic updating

**Comment by TheCodez** [comment]
Ok, I'll remove the option from preferences and change the refreshh buttons usage to enable/disable automatic preview

**Comment by amakaseev** [comment]
Its a very good

**Comment by TheCodez** [comment]
When i change the refresh button to enable/disable automatic refresh, then you can't do manual refresh anymore. Should I do it like the "Open Project" button and have the dropdown be enable/disable

**Comment by amakaseev** [comment]
Im add checkbox into toolbar near refresh button, one moment

**Pull request merged**
