### PR TITLE
Add Mouse Zoom to preview view

### PR DESCRIPTION
**Pull request by TheCodez**

### CODE REVIEW

**Comment by amakaseev** [comment]
it is remarkable, only make that a zoom worked in case of the pressed key Alt

**Comment by amakaseev** [comment]
what the functionality of scrolling of the image a magic mouse Apple would remain

**Comment by TheCodez** [comment]
What do you think about Ctrl + Mouse wheel?

**Comment by amakaseev** [comment]
look what button in textures a packer?
I think better to make also for a habit?

**Comment by amakaseev** [comment]
on MacOS the button a Alt and on Windows?

**Comment by amakaseev** [comment]
then add Alt only for MacOS

**Pull request merged**
